# Generated by Django 3.1.8 on 2021-11-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_auto_20211117_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='dogs',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='events',
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.owner'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.owner'),
        ),
    ]
