# Generated by Django 3.1.8 on 2021-11-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_auto_20211119_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='user',
            new_name='creator',
        ),
    ]
