# Generated by Django 3.1.8 on 2021-11-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_auto_20211120_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
