# Generated by Django 3.1.8 on 2021-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0012_auto_20211120_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
